# Generated by Django 5.2.16 on 2026-07-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64, verbose_name='通道')),
                ('alert_type', models.CharField(max_length=16, verbose_name='告警类型')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='分数')),
                ('message', models.TextField(blank=True, null=True, verbose_name='消息')),
                ('created_at', models.FloatField(verbose_name='创建时间')),
                ('status', models.CharField(default='active', max_length=16, verbose_name='状态')),
                ('verified_at', models.FloatField(blank=True, null=True, verbose_name='核验时间')),
                ('llm_verdict', models.CharField(blank=True, max_length=16, null=True, verbose_name='LLM裁决')),
                ('human_verdict', models.CharField(blank=True, max_length=16, null=True, verbose_name='人工裁决')),
                ('ingested_at', models.FloatField(verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'alert_records',
                'indexes': [models.Index(fields=['channel', 'created_at'], name='idx_alert_channel_time')],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64, verbose_name='通道')),
                ('timestamp', models.FloatField(verbose_name='时间戳')),
                ('l1_decision', models.CharField(blank=True, max_length=16, null=True, verbose_name='L1决策')),
                ('l1_score', models.FloatField(blank=True, null=True, verbose_name='L1分数')),
                ('l1_detail', models.TextField(blank=True, null=True, verbose_name='L1明细')),
                ('l2_score', models.FloatField(blank=True, null=True, verbose_name='L2分数')),
                ('l3_score', models.FloatField(blank=True, null=True, verbose_name='L3分数')),
                ('l3_rules', models.TextField(blank=True, null=True, verbose_name='L3规则')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='最终分数')),
                ('ingested_at', models.FloatField(verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '检测明细',
                'verbose_name_plural': '检测明细',
                'db_table': 'detection_results',
                'indexes': [models.Index(fields=['channel', 'timestamp'], name='idx_det_channel_time')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64, verbose_name='通道')),
                ('alert_type', models.CharField(max_length=16, verbose_name='告警类型')),
                ('alert_ts', models.FloatField(verbose_name='告警时间戳')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='诊断报告')),
                ('context_summary', models.TextField(blank=True, null=True, verbose_name='上下文摘要')),
                ('elapsed_sec', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('error', models.TextField(blank=True, null=True, verbose_name='错误')),
                ('llm_verdict', models.CharField(blank=True, max_length=16, null=True, verbose_name='LLM裁决')),
                ('created_at', models.FloatField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '诊断记录',
                'verbose_name_plural': '诊断记录',
                'db_table': 'diagnosis_records',
                'unique_together': {('channel', 'alert_type', 'alert_ts')},
            },
        ),
    ]
